### PR TITLE
Dependencies fix

### PR DESCRIPTION
**Pull request by magelite**
Updated clapp-discord dependencies to cli-table3.

Found this while trying to build a fresh docker container for gotbot.

### CODE REVIEW

**Comment by glorat** [comment]
Not sure what the nsp check is complaining about on this change...

**Comment by magelite** [comment]
Looks like an intermittent issue on the check...

Lets see if I can trigger another check.

**Comment by glorat** [comment]
Thx, looks good. I had tried to do this at home before but recall some quirk so I'll probably need to locally play with this before merging. I'll do this when I have time

**Comment by glorat** [comment]
BTW, @magelite , I don't know who you are. Would be good to chat. Ping me on discord... easiest place to find me is at https://discordapp.com/invite/R8QzpjW

**Pull request merged**
